{
 "title": "VMware ESXi",
 "tags": [
  "prometheus",
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "esxhost",
    "label": "esxhost",
    "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "ESXi host uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "vmware_host_boot_timestamp_seconds{host_name=~\"$esxhost\"} / 32"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_cpu_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "Host Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$esxhost\"}) * 100 / (vmware_host_memory_max{host_name=~\"$esxhost\"})"
    }
   ]
  },
  {
   "title": "DS datastore1 usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size{host_name=~\"$esxhost\", ds_name=~\"datastore1\"}) - (vmware_datastore_freespace_size{host_name=~\"$esxhost\", ds_name=~\"datastore1\"})) * 100 / (vmware_datastore_capacity_size{host_name=~\"$esxhost\", ds_name=~\"datastore1\"})"
    }
   ]
  },
  {
   "title": "DS datastore2 usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size{host_name=~\"$esxhost\", ds_name=~\"datastore2\"}) - (vmware_datastore_freespace_size{host_name=~\"$esxhost\", ds_name=~\"datastore2\"})) * 100 / (vmware_datastore_capacity_size{host_name=~\"$esxhost\", ds_name=~\"datastore2\"})"
    }
   ]
  },
  {
   "title": "DS backup_nfs usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size{host_name=~\"$esxhost\", ds_name=~\"backup_nfs\"}) - (vmware_datastore_freespace_size{host_name=~\"$esxhost\", ds_name=~\"backup_nfs\"})) * 100 / (vmware_datastore_capacity_size{host_name=~\"$esxhost\", ds_name=~\"backup_nfs\"})"
    }
   ]
  },
  {
   "title": "vm Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "rate(vmware_vm_mem_usage{host_name=~\"$esxhost\"}[5m]) / 4",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  },
  {
   "title": "Datastores Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size{host_name=~\"$esxhost\"}) - (vmware_datastore_freespace_size{host_name=~\"$esxhost\"})) * 100 / (vmware_datastore_capacity_size{host_name=~\"$esxhost\"})",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  {
   "title": "vm CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(vmware_vm_cpu_usagemhz{host_name=~\"$esxhost\"}[5m])",
     "legendFormat": "{{ vm_name }}"
    }
   ]
  }
 ]
}