{
 "title": "VMware Cluster Owerview",
 "description": "VMware ESXi single instance graphs.",
 "tags": [ "vmware" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(vmware_exporter_host_cluster_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cpu Core Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((vmware_exporter_host_cpu_cores and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Cpu Threads Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((vmware_exporter_host_cpu_threads and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Cpu Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((vmware_exporter_host_cpu_max and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})) * 1000 * 1000"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((vmware_exporter_host_memory_max and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Host Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((vmware_exporter_host_hardware_info and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Host In Maintenance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((vmware_exporter_host_maintenance_mode and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})==1) OR vector(0)"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((vmware_exporter_host_cpu_usage and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})) * 100 / sum((vmware_exporter_host_cpu_max and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }"
    }
   ]
  },
  {
   "title": "Max VM Cpu Ready on Cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((vmware_exporter_vm_cpu_ready_summation and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))/ 200",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Max VM Cpu Co-Stop on Cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((vmware_exporter_vm_cpu_costop_summation and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))/200",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_exporter_host_cpu_usage and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})) * 100 / sum((vmware_exporter_host_cpu_max and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((vmware_exporter_host_memory_usage and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})) * 100 / sum((vmware_exporter_host_memory_max and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Max VM Ballooning",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((vmware_exporter_vm_mem_vmmemctl_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Max VM Swapped",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max((vmware_exporter_vm_mem_swapped_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Cluster Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(((vmware_exporter_host_memory_usage and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})) * 100) / sum((vmware_exporter_host_memory_max and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Nodes Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vmware_exporter_host_hardware_info{} -0 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_exporter_host_memory_max{} -0",
     "legendFormat": "Host Memory Max"
    },
    {
     "expr": "vmware_exporter_host_cpu_cores{} -0",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "time() - vmware_exporter_host_boot_timestamp_seconds{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_exporter_host_cpu_threads{} ",
     "legendFormat": "Cpu Threads"
    },
    {
     "expr": "vmware_exporter_host_cpu_usage{} / vmware_exporter_host_cpu_max{} * 100",
     "legendFormat": "Cpu Usage"
    },
    {
     "expr": "vmware_exporter_host_memory_usage{} / vmware_exporter_host_memory_max{} * 100",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(vmware_exporter_vm_net_received_average{}) by (host_name)",
     "legendFormat": "Net Received"
    },
    {
     "expr": "sum(vmware_exporter_vm_net_transmitted_average{}) by (host_name)",
     "legendFormat": "Net Transmitted"
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_exporter_vm_net_received_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))+sum((vmware_exporter_vm_net_transmitted_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Network Receive Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_exporter_vm_net_received_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Network Transmit Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_exporter_vm_net_transmitted_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster}}"
    }
   ]
  },
  {
   "title": "Cluster Network Broadcast RX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_exporter_vm_net_broadcastrx_summation and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Network Broadcast TX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_exporter_vm_net_broadcasttx_summation and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster}}"
    }
   ]
  },
  {
   "title": "Host Network Multicast RX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_exporter_vm_net_multicastrx_summation and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Network Multicast TX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_exporter_vm_net_multicasttx_summation and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Disk Read And Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_exporter_vm_disk_read_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))+sum((vmware_exporter_vm_disk_write_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Disk Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_exporter_vm_disk_read_average{cluster_name =~\"$cluster\"})",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Disk Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum((vmware_exporter_vm_disk_write_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}))",
     "legendFormat": "{{ $cluster }}"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Hosts connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_exporter_host_connected and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Hosts not connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_exporter_host_connected == 0 and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Red alarms (hosts)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_exporter_host_red_alarms and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Yellow alarms (hosts)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_exporter_host_yellow_alarms and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "VMs powered on",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_exporter_vm_power_state == 1 and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Red alarms (VMs)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_exporter_vm_red_alarms and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  { "title": "Host network and storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Host network throughput per NIC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by (host_name, nic)(vmware_exporter_host_net_bytesrx_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})",
     "legendFormat": "rx {{host_name}} {{nic}}"
    },
    {
     "expr": "sum by (host_name, nic)(vmware_exporter_host_net_bytestx_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})",
     "legendFormat": "tx {{host_name}} {{nic}}"
    }
   ]
  },
  {
   "title": "Host network errors and drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (host_name)(vmware_exporter_host_net_errorsrx_summation and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})",
     "legendFormat": "errors rx {{host_name}}"
    },
    {
     "expr": "sum by (host_name)(vmware_exporter_host_net_errorstx_summation and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})",
     "legendFormat": "errors tx {{host_name}}"
    },
    {
     "expr": "sum by (host_name)(vmware_exporter_host_net_droppedrx_summation and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})",
     "legendFormat": "dropped rx {{host_name}}"
    },
    {
     "expr": "sum by (host_name)(vmware_exporter_host_net_droppedtx_summation and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})",
     "legendFormat": "dropped tx {{host_name}}"
    }
   ]
  },
  {
   "title": "Datastore latency per host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (host_name)(vmware_exporter_host_datastore_totalreadlatency_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})",
     "legendFormat": "read {{host_name}}"
    },
    {
     "expr": "max by (host_name)(vmware_exporter_host_datastore_totalwritelatency_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})",
     "legendFormat": "write {{host_name}}"
    }
   ]
  },
  {
   "title": "Datastore throughput per host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by (host_name)(vmware_exporter_host_datastore_read_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})",
     "legendFormat": "read {{host_name}}"
    },
    {
     "expr": "sum by (host_name)(vmware_exporter_host_datastore_write_average and on (host_name) vmware_exporter_host_cluster_info{cluster=~\"$cluster\"})",
     "legendFormat": "write {{host_name}}"
    }
   ]
  }
 ]
}